export const GET_PHONE_DATA = "GET_PHONE_DATA";
// export const ADD_CHILD_LIST = "ADD_CHILD_LIST";
// export const DEL_CHILD_LIST = "DEL_CHILD_LIST";
// export const UPDATE_CHILD_LIST = "UPDATE_CHILD_LIST";
export const SAVE_PHONE_DATA = "SAVE_PHONE_DATA";
export const SAVE_ACTIVITY_DATA = "SAVE_ACTIVITY_DATA";
export const SAVE_SHOP_PROMATION = "SAVE_SHOP_PROMATION"