export const START_GET_DATA="START_GET_DATA";
export const SAVE_TABLE_DATA="SAVE_TABLE_DATA";
export const REMOVE_TABLE_DATA="REMOVE_TABLE_DATA";
export const PUBLISH_TABLE_DATA="PUBLISH_TABLE_DATA";
export const UPDATE_TABLE_DATA="UPDATE_TABLE_DATA";